#ifndef CONFIG_H
#define CONFIG_H

#define BAUDRATE 115200

#define BUTTON_PIN 7
#define LED_PIN 2

#define LED_TASK_RECURRENCE 200
#define LED_TASK_OFFSET 10
#define BUTTON_PIN 7 
#define LED_PIN 2 
#define FLASHING_LED_PIN 1 
#define INCREASE_BUTTON_PIN 6 
#define DECREASE_BUTTON_PIN 5 

#endif // CONFIG_H